language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
script:
  - pytest --cov ./
after_success:
    - codecov